name: gbc_coachia
description: A Flutter-based mobile application designed to empower entrepreneurs and freelancers with comprehensive AI-powered business management tools.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  get_it: ^7.6.0
  go_router: ^10.1.2
  uuid: ^4.5.1
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.63.0
  flutter_markdown: ^0.6.17
  table_calendar: ^3.0.9
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.0.0
  skeletonizer: ^0.9.0
  google_fonts: ^6.2.1
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
