name: gbc_coachia
description: Application mobile d'aide à la gestion d'entreprise pour entrepreneurs et freelances avec IA.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.9
  path_provider: ^2.1.2
  http: ^1.2.1
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  url_launcher: ^6.2.4
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
