name: gbc_coachia
description: "Application d'assistance entrepreneuriale IA pour GBC"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency injection
  get_it: ^7.6.4
  
  # Routing
  go_router: ^13.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  connectivity_plus: ^4.0.2
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
